; アナログスティックの上下左右を十字キーに割り当てます。

MACROFIRE-REMAP = 1

[Remap]
0.RealButtons = ANALOGUP
0.RemapButtons = UP
1.RealButtons = ANALOGRIGHT
1.RemapButtons = RIGHT
2.RealButtons = ANALOGDOWN
2.RemapButtons = DOWN
3.RealButtons = ANALOGLEFT
3.RemapButtons = LEFT
