;十字キーの上下左右をアナログスティックに割り当てます。

MACROFIRE-REMAP = 1

[Remap]
0.RealButtons = UP
0.RemapButtons = ANALOGUP
1.RealButtons = RIGHT
1.RemapButtons = ANALOGRIGHT
2.RealButtons = DOWN
2.RemapButtons = ANALOGDOWN
3.RealButtons = LEFT
3.RemapButtons = ANALOGLEFT
