/*=========================================================
	
	mfstrings_jp.h
	
	MacroFire内で使用する文字列定数。
	
=========================================================*/
#ifndef MFSTRINGS_H
#define MFSTRINGS_H

#define MF_STR_TITLE "MacroFire %s ゲーム内メニュー"

#define MF_STR_LIMIT_WEBBROWSER "インターネットブラウザ動作中にこの機能\を使うことはできません。"

#define MF_STR_ERROR                     "エラー"
#define MF_STR_ERROR_INVALID_CONF        "有効なMacroFireの設定ファイルではありません"
#define MF_STR_ERROR_UNSUPPORTED_VERSION "サポートしていないバージョンの設定ファイルです"
#define MF_STR_ERROR_NOT_ENOUGH_MEMORY   "メモリが足りません"

#define MF_STR_CTRL_ON            "有効"
#define MF_STR_CTRL_OFF           "無効"
#define MF_STR_CTRL_MOVE          "移動"
#define MF_STR_CTRL_PAGEMOVE      "ページ移動"
#define MF_STR_CTRL_BACK          "戻る"
#define MF_STR_CTRL_TOGGLE_SWITCH "切り替える"
#define MF_STR_CTRL_ENTER         "開く"
#define MF_STR_CTRL_ASSIGN        "割り当てる"
#define MF_STR_CTRL_DECREASE      "減少"
#define MF_STR_CTRL_INCREASE      "増加"
#define MF_STR_CTRL_EDIT          "編集"
#define MF_STR_CTRL_CHANGE_OPTION "変更"
#define MF_STR_CTRL_EXECUTE       "実行"
#define MF_STR_CTRL_EXIT          "終了"

#define MF_STR_SAVE    "セーブ"
#define MF_STR_LOAD    "ロード"
#define MF_STR_SAVING  "%sへセーブ中..."
#define MF_STR_LOADING "%sをロード中..."

#define MF_STR_HOME_MACROFIRE_ENGINE        "MacroFire エンジン"
#define MF_STR_HOME_MACROFIRE_PREFERENCE    "設定"
#define MF_STR_HOME_SET_MENU_BUTTON         "メニュー起動ボタン"
#define MF_STR_HOME_SET_TOGGLE_BUTTON       "エンジン状態切り替えボタン"
#define MF_STR_HOME_STAT_NOTIFICATION       "エンジン状態の通知"
#define MF_STR_HOME_ANALOG_STICK_ADJUSTMENT "アナログスティックの感度調整"
#define MF_STR_HOME_FUNCTION                "機能\ "

#define MF_STR_FUNCTION_REMAP     "ボタン再割り当て設定"
#define MF_STR_FUNCTION_RAPIDFIRE "連射設定"
#define MF_STR_FUNCTION_MACRO     "マクロ設定"

#define MF_STR_ASA_DESC          "アナログスティックの感度調整を行います。"
#define MF_STR_ASA_MOVEMENT      "アナログスティック"
#define MF_STR_ASA_DEADZONE      "デッドゾーン"
#define MF_STR_ASA_SENSITIVITY   "感度　　　　"
#define MF_STR_ASA_ORIGIN_X      "中心とするX座標"
#define MF_STR_ASA_ORIGIN_Y      "中心とするY座標"
#define MF_STR_ASA_TEST_DIR      "アナログスティックのテスト(方向):"
#define MF_STR_ASA_TEST_MOVE     "アナログスティックのテスト(座標):"
#define MF_STR_ASA_TEST_MOVE_RAW "　　　生座標"
#define MF_STR_ASA_TEST_MOVE_ADJ "調整後の座標"

#define MF_STR_REMAP_DESC               "ボタン再割り当てリスト。"
#define MF_STR_REMAP_SUGGEST            "<△ボタンを押すと新しい再割り当て設定を追加>"
#define MF_STR_REMAP_BUTTON             "　　再割り当て先"
#define MF_STR_REMAP_BUTTON_DISABLE     "無効"
#define MF_STR_REMAP_CLEAR              "クリア"
#define MF_STR_REMAP_CTRL_SWITCH_COLUMN "カラム切り替え"
#define MF_STR_REMAP_CLEAR_WARN_TITLE   "警告"
#define MF_STR_REMAP_CLEAR_WARN_MSG     "全ての再割り当て設定を削除します。\nよろしいですか?"
#define MF_STR_REMAP_CTRL_ADD           "追加"
#define MF_STR_REMAP_CTRL_DELETE        "削除"
#define MF_STR_REMAP_CTRL_EDIT_REMAP    "再割り当てボタンを編集"
#define MF_STR_REMAP_DIAGBUTTON_REAL    "再割り当てするボタン"
#define MF_STR_REMAP_DIAGBUTTON_REMAP   "再割り当て先ボタン"
#define MF_STR_REMAP_DIAGGETFN_SAVE     "再割り当て設定の保存"
#define MF_STR_REMAP_DIAGGETFN_LOAD     "再割り当て設定の読み込み"

#define MF_STR_RAPIDFIRE_DESC                      "ボタンごとの連射モードを選択してください。" 
#define MF_STR_RAPIDFIRE_MODE_LABEL                "モード"
#define MF_STR_RAPIDFIRE_BUTTON_TRIANGLE           "△ボタン"
#define MF_STR_RAPIDFIRE_BUTTON_CIRCLE             "○ボタン"
#define MF_STR_RAPIDFIRE_BUTTON_CROSS              "×ボタン"
#define MF_STR_RAPIDFIRE_BUTTON_SQUARE             "□ボタン"
#define MF_STR_RAPIDFIRE_BUTTON_LTRIGGER           "Ｌボタン"
#define MF_STR_RAPIDFIRE_BUTTON_RTRIGGER           "Ｒボタン"
#define MF_STR_RAPIDFIRE_BUTTON_UP                 "十\字キー↑　　"
#define MF_STR_RAPIDFIRE_BUTTON_RIGHT              "十\字キー→　　"
#define MF_STR_RAPIDFIRE_BUTTON_DOWN               "十\字キー↓　　"
#define MF_STR_RAPIDFIRE_BUTTON_LEFT               "十\字キー←　　"
#define MF_STR_RAPIDFIRE_BUTTON_START              "スタートボタン"
#define MF_STR_RAPIDFIRE_BUTTON_SELECT             "セレクトボタン"
#define MF_STR_RAPIDFIRE_WAITCONTROL_LABEL         "待機時間設定"
#define MF_STR_RAPIDFIRE_WAITCONTROL_PRESS_DELAY   "ボタンを押した状態を維持する時間"
#define MF_STR_RAPIDFIRE_WAITCONTROL_RELEASE_DELAY "ボタンを放した状態を維持する時間"
#define MF_STR_RAPIDFIRE_FILE_LABEL                "ファイル"
#define MF_STR_RAPIDFIRE_MANUAL_NORMAL             "Normal    : 何もしない."
#define MF_STR_RAPIDFIRE_MANUAL_RAPID              "Rapid     : ボタンを押している間だけ連射."
#define MF_STR_RAPIDFIRE_MANUAL_AUTORAPID          "Auto-Rapid: 常に連射."
#define MF_STR_RAPIDFIRE_MANUAL_HOLD               "Hold      : ボタンを押しっぱなし状態と放している状態を切り替える."
#define MF_STR_RAPIDFIRE_MANUAL_AUTOHOLD           "Auto-Hold : 常にボタンを押しっぱなし状態."
#define MF_STR_RAPIDFIRE_DIAGGETFN_SAVE            "連射設定の保存"
#define MF_STR_RAPIDFIRE_DIAGGETFN_LOAD            "連射設定の読み込み"

#define MF_STR_MACRO_DESC           "操作を選んでください。"
#define MF_STR_MACRO_SLOT           "マクロスロット"
#define MF_STR_MACRO_PREF_LABEL     "設定"
#define MF_STR_MACRO_PREF_RUN_STOP  "実行/停止ボタン"
#define MF_STR_MACRO_PREF_LOOP_NUM  "繰り返し回数"
#define MF_STR_MACRO_CONTROL_LABEL  "操作"
#define MF_STR_MACRO_CONTROL_RUN    "実行"
#define MF_STR_MACRO_CONTROL_STOP   "停止"
#define MF_STR_MACRO_CONTROL_EDIT   "編集"
#define MF_STR_MACRO_CONTROL_CLEAR  "クリア"
#define MF_STR_MACRO_RECORD_LABEL   "リアルタイム記録"
#define MF_STR_MACRO_RECORD_START   "開始"
#define MF_STR_MACRO_RECORD_APPEND  "追記"
#define MF_STR_MACRO_RECORD_STOP    "停止"
#define MF_STR_MACRO_RECORD_ANALOG  "アナログスティックの記録"
#define MF_STR_MACRO_FILE_LABEL     "ファイル"
#define MF_STR_MACRO_STAT_RECORDING "(記録中)"
#define MF_STR_MACRO_STAT_RUNNING   "(実行中)"
#define MF_STR_MACRO_STAT_AVAILABLE "(利用可能\)"
#define MF_STR_MACRO_STAT_EMPTY     ""
#define MF_STR_MACRO_CTRL_PREV      "前"
#define MF_STR_MACRO_CTRL_NEXT      "次"
#define MF_STR_MACRO_CTRL_EDIT_NAME "マクロ名を編集"
#define MF_STR_MACRO_DIAGSOSK_NAME  "マクロ名"
#define MF_STR_MACRO_LOOP_INFINITY  "無限"
#define MF_STR_MACRO_STOP_RECORD    "記録を停止しています..."
#define MF_STR_MACRO_STOP_RUN       "中断."
#define MF_STR_MACRO_CLEAR          "マクロをクリアしています..."
#define MF_STR_MACRO_DIAGGETFN_SAVE "マクロの保存"
#define MF_STR_MACRO_DIAGGETFN_LOAD "マクロの読み込み"
#define MF_STR_MACRO_ENGINE_IS_OFF  "MacroFire エンジンが無効になっています。"

#endif
